version: "3"
services:
  app:
    build:
      context: .
      target: production-build-stage
      dockerfile: ./docker/App.Dockerfile
    container_name: app
    volumes:
      - ./:/var/www/app:cached
      - /var/www/app/node_modules # anonymous volume for node_modules only
    restart: always
    ports:
      - 3000:3000
    environment:
      - SERVER_PORT=3000
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DB=postgres
      - POSTGRESQL_HOST=postgres
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=super-secret
      - REFRESH_TOKEN=REFRESH_TOKEN
      - ACCESS_TOKEN=ACCESS_TOKEN
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
  # migrations:
  #   build:
  #     context: .
  #     target: migrations-build-stage
  #     dockerfile: ./docker/App.Dockerfile
  #   container_name: migrations
  #   volumes:
  #     - /app/node_modules
  #   depends_on:
  #     - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
